const { EntitySchema } = require('typeorm');

const Reserva = new EntitySchema({
  name: 'Reserva',
  tableName: 'reservas',
  columns: {
    id: { primary: true, type: 'int', generated: true },
    estado: { nullable: true, type: 'varchar', length: 50, default: 'confirmada' },
    fecha_inicio: { nullable: true, type: 'timestamp' },
    fecha_fin: { nullable: true, type: 'timestamp' },
    estudiante_id: { nullable: true, type: 'int' },
    instructor_id: { nullable: true, type: 'int' },
    vehiculo_id: { type: 'int', nullable: true },
    sede_id: { nullable: true, type: 'int' },
    tipo_clase_id: { type: 'int', nullable: true },
    created_at: { nullable: true, type: 'timestamp', createDate: true },
  },
  relations: { nullable: true,
    estudiante: {
      type: 'many-to-one',
      target: 'Usuario',
      joinColumn: { name: 'estudiante_id' , nullable: true },
    },
    instructor: { nullable: true,
      type: 'many-to-one',
      target: 'Usuario',
      joinColumn: { name: 'instructor_id' },
    },
    vehiculo: { nullable: true,
      type: 'many-to-one',
      target: 'Vehiculo',
      joinColumn: { name: 'vehiculo_id' },
    },
    sede: { nullable: true,
      type: 'many-to-one',
      target: 'Sede',
      joinColumn: { name: 'sede_id' },
    },
    tipoClase: { nullable: true,
      type: 'many-to-one',
      target: 'TipoClase',
      joinColumn: { name: 'tipo_clase_id' },
      nullable: true,
    },
  },
});

module.exports = Reserva;
